### ISSUE TITLE
ImportError Issue

### ISSUE THREAD

**Issue by waddah12alhajar** [nl4dv/nl4dv#16]
Hello,
After I run all the steps as specified in the application section at https://nl4dv.github.io/nl4dv/documentation.html,  I am getting the following error by running (python app.py)
ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\wadda\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)
Do you have any idea how to solve the importing issue?
Thanks

**Comment by arpitnarechania** [comment]
Hello,
Thanks for your note. I looked up this error and found an explanation [in this stackoverflow post](https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections). It looks like there was a change in the `collections` module across Python versions. 
We would have to release a new version for Python 3.10+.

**Comment by rmitra34** [comment]
Hello, 
We have pushed a new release of NL4DV 2.1.0 to [PyPi](https://pypi.org/project/nl4dv/). Please let us know if you run into any more issues.
