### ISSUE TITLE
Is there a way to use a data frame instead of a file path? 

### ISSUE THREAD

**Issue by shariqak14** [nl4dv/nl4dv#5]
Really amazing work here! 

Is it possible to pass a data frame as the `data_url`? I am trying to use this with a MySQL database, and I would much rather have the data be stored in the session temporarily (as a data frame) rather than it be cached on the disk permanently (or until someone deletes it).

If you can offer any advice, that will be much appreciated!

**Comment by arpitnarechania** [comment]
@shariqak14 , thanks for this; for sure we can start supporting `raw_data` inputs. Check out the below potential data input formats:

1. list of lists (attributes form the first list item, e.g. [["Age", "Salary"], [19, 1000], [21, 1320], [25, 4330], ...]
2. dict of lists (attributes are dict keys, e.g., { "age": [19, 21, 25, ...], "salary": [1000, 1320, 4330, ...]}

I will add support for these in the next three-four days. Is there an alternative input format that you think will be useful?

**Comment by shariqak14** [comment]
Thanks a ton, @arpitnarechania! Either format works for me.

**Comment by arpitnarechania** [comment]
@shariqak14 , NL4DV now supports passing local file objects as well as files hosted on the web using the new `data_url` parameter. For your use-case, you can use the `data_value` param that lets you input a `list`, `dict`, or `a pandas dataframe`. 

Please check the [updated documentation](https://nl4dv.github.io/nl4dv/documentation.html) for examples. These changes are available in a new version, [nl4dv==0.0.4](https://pypi.org/project/nl4dv/). 

With this, I am closing this issue. Let me know in case of any issue.

**Comment by shariqak14** [comment]
@arpitnarechania, thank you so much for this addition. It works perfectly!
